export const actionsJobs = {
    RECEIVE_JOBS_DATA: "RECEIVE_JOBS_DATA",
    RECEIVE_JOBS_DETAILS: "RECEIVE_JOBS_DETAILS",
    SET_JOBS_LIST: "SET_JOBS_LIST",
    CLEAR_JOBS_FILTER_ACTION: "CLEAR_JOBS_FILTER_ACTION",
    UPDATE_JOBS_FILTER_ACTION: "UPDATE_JOBS_FILTER_ACTION"
}

export const actionsInvoices = {
    RECEIVE_INVOICES_DATA: "RECEIVE_INVOICES_DATA",
    RECEIVE_INVOICES_DETAILS: "RECEIVE_INVOICES_DETAILS",
    SET_INVOICES_LIST: "SET_INVOICES_LIST",
    CLEAR_INVOICES_FILTER_ACTION: "CLEAR_INVOICES_FILTER_ACTION",
    UPDATE_INVOICES_FILTER_ACTION: "UPDATE_INVOICES_FILTER_ACTION",
    RECEIVE_INVOICE_CREDIT: "RECEIVE_INVOICE_CREDIT",
}

export const actionsOrders = {
    RECEIVE_ORDERS_DATA: "RECEIVE_ORDERS_DATA",
    RECEIVE_ORDERS_DETAILS: "RECEIVE_ORDERS_DETAILS",
    SET_ORDERS_LIST: "SET_ORDERS_LIST",
    CLEAR_ORDERS_FILTER_ACTION: "CLEAR_ORDERS_FILTER_ACTION",
    UPDATE_ORDERS_FILTER_ACTION: "UPDATE_ORDERS_FILTER_ACTION"
}

export const actionsCustomers = {
    RECEIVE_CUSTOMERS_DATA: "RECEIVE_CUSTOMERS_DATA",
    RECEIVE_CUSTOMERS_DETAILS: "RECEIVE_CUSTOMERS_DETAILS",
    SET_CUSTOMERS_LIST: "SET_CUSTOMERS_LIST",
    CLEAR_CUSTOMERS_FILTER_ACTION: "CLEAR_CUSTOMERS_FILTER_ACTION",
    UPDATE_CUSTOMERS_FILTER_ACTION: "UPDATE_CUSTOMERS_FILTER_ACTION",
    SET_UPDATE_ERRORS: "SET_UPDATE_ERRORS"
}